GET http://localhost:3000/api/v1.0/check-version

###
GET http://localhost:3000/api/v1.0/songs

###
GET http://localhost:3000/api/v1.0/songs/1

###
POST http://localhost:3000/api/v1.0/songs
Content-Type: application/json

{
  "title": "Lasting Lover 2024",
  "artists": [1],
  "releaseDate": "2024-06-01",
  "duration": "03:45",
  "lyrics": "Sample lyrics for the new song."
}

###
DELETE http://localhost:3000/api/v1.0/songs/2

###
PUT http://localhost:3000/api/v1.0/songs/1
Content-Type: application/json

{
  "title": "Lasting Lover Updated",
  "artists": [1],
  "releaseDate": "2024-06-01",
  "duration": "03:45",
  "lyrics": "Sample lyrics for the new song."
}

//// USERS /////

###
POST http://localhost:3000/api/v1.0/auth/signup
Content-Type: application/json

{
  "firstName": "Toheeb",
  "lastName": "Alfa",
  "email": "toheeb@example.com",
  "password": "password"
}

###
POST http://localhost:3000/api/v1.0/auth/login
Content-Type: application/json

{
  "email": "toheeb@example.com",
  "password": "password"
}

###
GET http://localhost:3000/api/v1.0/profile
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRvaGVlYkBleGFtcGxlLmNvbSIsInN1YiI6MiwiaWF0IjoxNzcyOTAyMjMxLCJleHAiOjE3NzI5MDU4MzEsImF1ZCI6Im5lc3Rwcm9qLXVzZXJzIiwiaXNzIjoibmVzdHByb2oiLCJqdGkiOiI4MjAxN2Q2Ni0yNzlkLTQ3NjYtYmNlOC0yMWI3ZDI5ZGQzNmYifQ.Q0AAzeE2TR1wXdshovkIi435LO_BFI5U5HeaWgCQxN4


/// Artist
###
GET http://localhost:3000/api/v1.0/artist


###
POST http://localhost:3000/api/v1.0/artist/create