GET http://localhost:3000/api/v1.0/check-version

###
GET http://localhost:3000/api/v1.0/songs

###
GET http://localhost:3000/api/v1.0/songs/1

###
POST http://localhost:3000/api/v1.0/songs
Content-Type: application/json

{
  "title": "Lasting Lover 2024",
  "artists": [1],
  "releaseDate": "2024-06-01",
  "duration": "03:45",
  "lyrics": "Sample lyrics for the new song."
}

###
DELETE http://localhost:3000/api/v1.0/songs/2

###
PUT http://localhost:3000/api/v1.0/songs/1
Content-Type: application/json

{
  "title": "Lasting Lover Updated",
  "artists": [1],
  "releaseDate": "2024-06-01",
  "duration": "03:45",
  "lyrics": "Sample lyrics for the new song."
}

//// AUTH /////

###
POST http://localhost:3000/api/v1.0/auth/signup
Content-Type: application/json

{
  "firstName": "Ayos",
  "lastName": "Maffs",
  "email": "ayos@example.com",
  "password": "password"
}

###
POST http://localhost:3000/api/v1.0/auth/login
Content-Type: application/json

{
  "email": "ayo@example.com",
  "password": "password"
}

/// Enable 2FA
###
GET http://localhost:3000/api/v1.0/auth/enable-2fa

/// Disable 2FA
###
GET http://localhost:3000/api/v1.0/auth/disable-2fa

/// Validate 2FA token
###
POST http://localhost:3000/api/v1.0/auth/validate-2fa
Content-Type: application/json

{
  "token": "858412"
}


//// USER //////
/// Profile
###
GET http://localhost:3000/api/v1.0/profile
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRvaGVlYkBleGFtcGxlLmNvbSIsInN1YiI6MiwiaWF0IjoxNzcyOTAyMjMxLCJleHAiOjE3NzI5MDU4MzEsImF1ZCI6Im5lc3Rwcm9qLXVzZXJzIiwiaXNzIjoibmVzdHByb2oiLCJqdGkiOiI4MjAxN2Q2Ni0yNzlkLTQ3NjYtYmNlOC0yMWI3ZDI5ZGQzNmYifQ.Q0AAzeE2TR1wXdshovkIi435LO_BFI5U5HeaWgCQxN4


###
GET http://localhost:3000/api/v1.0/auth/profile
Authorization: Bearer fc78a359-1903-4095-ab64-79cc2e86be9e


/// Artist
###
GET http://localhost:3000/api/v1.0/artist


###
POST http://localhost:3000/api/v1.0/artist/create